# Generated by Django 5.2 on 2025-12-08 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.lab'),
        ),
    ]
