# Generated by Django 5.2 on 2025-12-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_add_purpose_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason why the admin rejected this request', null=True),
        ),
    ]
