# Generated by Django 5.2 on 2025-12-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0010_alter_equipment_id_alter_lab_id'),
        ('reservations', '0010_alter_reservation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='reservations', to='labs.equipment'),
        ),
    ]
