# Generated by Django 6.0 on 2025-12-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_alter_reservation_id'),
        ('reservations', '0013_reservation_equipment_through'),
    ]

    operations = [
    ]
