# Generated by Django 6.0 on 2025-12-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_alter_equipment_id_alter_lab_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='last_maintenance',
            field=models.DateField(),
        ),
    ]
