# Generated by Django 6.0 on 2025-12-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_alter_equipment_last_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='safety_guidelines',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
