# Generated by Django 5.2 on 2025-12-09 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0005_alter_equipment_id_alter_lab_id'),
        ('labs', '0005_lab_safety_guidelines'),
    ]

    operations = [
    ]
