# Generated by Django 5.2 on 2025-12-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0006_merge_20251209_1607'),
        ('labs', '0006_merge_20251209_1640'),
    ]

    operations = [
    ]
