# Generated by Django 6.0 on 2025-12-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0009_equipment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
