# Generated by Django 6.0 on 2025-12-09 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0010_alter_equipment_id_alter_lab_id'),
        ('labs', '0010_equipment_quantity'),
    ]

    operations = [
    ]
