# Generated by Django 6.0 on 2025-12-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0011_merge_20251209_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
