# Generated by Django 5.2 on 2025-12-09 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0011_merge_20251209_2153'),
        ('labs', '0012_alter_equipment_id_alter_lab_id'),
    ]

    operations = [
    ]
