# Generated by Django 6.0 on 2025-12-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('reservation', 'Reservation Update'), ('announcement', 'Public Announcement')], default='reservation', max_length=20),
        ),
    ]
