<<<<<<< HEAD
# Generated by Django 5.2 on 2025-12-08 16:23
=======
# Generated by Django 5.2 on 2025-12-09 00:43
>>>>>>> 22ddbdaca5825a5a4d510007439093a7022792ad

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
