<<<<<<< HEAD
# Generated by Django 6.0 on 2025-12-09 01:46
=======
# Generated by Django 5.2 on 2025-12-08 16:23
>>>>>>> 68db2a78db61fc3147400310eacb7a3445ae0e86

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
